name: Trigger Netlify Build
on:
  schedule:
    # Run at 0200 daily
    - cron: '00 02 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/602bf4c868455d537695c905