name: Trigger Netlify Build
on:
  workflow_dispatch:
  schedule:
    # Run at 0200 daily
    - cron: '00 02 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/60777c7ccc0d6a7953de7e0b
